services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a123456A!
      POSTGRES_DB: testdb
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
