services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"   # Redis 기본 포트
      - "8001:8001"   # RedisInsight용 포트
    volumes:
      - redis-stack-data:/data
    networks:
      - redis-stack-network

volumes:
  redis-stack-data:

networks:
  redis-stack-network:
    driver: bridge
